// Users
export const GET_USER = 'GET_USER';
export const USER_STATUS = 'USER_STATUS';

// Search
export const FETCH_REPOS_BEGIN = 'FETCH_REPOS_BEGIN';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const FETCH_REPOS_FAILURE = 'FETCH_REPOS_FAILURE';
export const CLEAR_REPOS = 'CLEAR_REPOS';
export const NO_MATCH_FOUND = 'NO_MATCH_FOUND';

// Feedback
export const GET_FEEDBACK = 'GET_FEEDBACK';
export const DELETE_FEEDBACK_ITEM = 'DELETE_FEEDBACK_ITEM';
export const UPDATE_FEEDBACK_ITEM = 'UPDATE_FEEDBACK_ITEM';
export const SUBMIT_FEEDBACK_ITEM = 'SUBMIT_FEEDBACK_ITEM';

